version: "3.8"
services:
  bitcoind:
    image: "ruimarinho/bitcoin-core:0.20"
    command:
      - -testnet
      - -server
      - -par=1
      - -maxuploadtarget=200
      - -blocksonly
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=rpcuser
      - -rpcpassword=rpcpassword
      - -fallbackfee=0.0002
    ports:
      - "18332:18332"
    volumes:
      - ./cache:/home/bitcoin/.bitcoin/testnet3
    restart: unless-stopped
  vault:
    image: "interlayhq/interbtc-clients:vault-parachain-metadata-testnet-1-5-4"
    command:
      - vault
      - --bitcoin-rpc-url
      - "http://bitcoind:18332"
      - --bitcoin-rpc-user
      - rpcuser
      - --bitcoin-rpc-pass
      - rpcpassword
      - --keyname
      - interbtcvault
      - --keyname
      - interbtcvault
      - --auto-register-with-faucet-url
      - "https://api-testnet.interlay.io/faucet"
      - --btc-parachain-url
      - "wss://api-testnet.interlay.io/parachain"
      - --collateral-currency-id
      - KSM
    environment:
      RUST_LOG: info
    volumes:
      - type: bind
        source: ./keyfile.json
        target: /keyfile.json
    restart: unless-stopped
